# SPDX-License-Identifier: Apache-2.0
"""Faithful production port of the frozen A9-SOTA-001 Article 9 assembly.

Given the per-document component outputs of the validated Article 9 stack
(SecuRedact base ``sec``, BardsAI ``bard``, contained GLiNER ``gliner``, and the
BGE-M3 semantic proposer's generic ``gen`` + decomposed ``gen_dec`` scores), this
module reproduces the EXACT frozen union + confusion-containment algorithm from
``sota/common.py:evaluate_securedact``. It is deterministic, torch-free, and is
the authoritative correctness anchor for the production promotion (it is tested
directly against the frozen ``securedact_full.json`` predictions).

The frozen a9-sota-001 full system was generated by ``evaluate_securedact`` with
a decomposition-score file (``a9-quality-006/genetic_decomposition_scores.json``)
that contains ONLY the four included genetic hypotheses. Its ``gen_dec`` therefore
had no ``pol_*`` / ``sex_*`` keys, so the political/sex-life *decomposition*
booster was inactive in the validated artifact: political/sex-life derive from
generic BGE (the GEN4 contribution) plus the detector stack, while only the
gated GENETIC decomposition adds its category. This port reproduces that exact
behaviour and therefore the freeze-manifest metrics.
"""

from __future__ import annotations

from ..models import EntityType
from .article9_hypotheses import (
    DECOMPOSED_GENETIC_D,
    FROZEN_G,
    GEN4,
    GEN_KEYS,
    GENETIC_CONFUSION_PARTNERS,
    GENETIC_GUARD,
)


def _genetic_decision(
    sec: set[EntityType],
    bard: set[EntityType],
    gliner: set[EntityType],
    gen: dict[EntityType, float],
    gen_dec: dict[str, float],
) -> bool:
    """Return whether ``GENETIC_DATA`` is proposed, per the frozen genetic guard.

    Faithful port of ``sota/common.py:target_decision`` for the genetic target,
    evaluated against the frozen decomposition score file, which contains only
    the four included genetic hypotheses. Mirrors the research code exactly.
    """

    threshold, guard, margin = (DECOMPOSED_GENETIC_D, GENETIC_GUARD, None)
    stack = (
        set(sec)
        | set(bard)
        | set(gliner)
        | {category for category in GEN4 if gen.get(category, 0.0) >= FROZEN_G}
    )
    stack_other = stack - {EntityType.GENETIC_DATA}
    generic_hit = gen.get(EntityType.GENETIC_DATA, 0.0) >= FROZEN_G
    best = max((gen_dec.get(key, 0.0) for key in GEN_KEYS), default=0.0)
    partner = max(
        (gen.get(category, 0.0) for category in GENETIC_CONFUSION_PARTNERS),
        default=0.0,
    )
    hard = set(GENETIC_CONFUSION_PARTNERS)
    decomp_hit = False
    if best >= threshold:
        if guard == "none":
            decomp_hit = True
        elif guard == "hard":
            decomp_hit = not (stack_other & hard)
        elif guard == "margin":
            decomp_hit = partner == 0.0 or best - partner >= (margin or 0.0)
        elif guard == "margin_hard":
            decomp_hit = (not (stack_other & hard)) and (
                partner == 0.0 or best - partner >= (margin or 0.0)
            )
    return generic_hit or decomp_hit


def assemble_article9_set(
    sec: set[EntityType],
    bard: set[EntityType],
    gliner: set[EntityType],
    gen: dict[EntityType, float],
    gen_dec: dict[str, float],
) -> set[EntityType]:
    """Reproduce the frozen ``securedact_full`` category set for one document.

    Line-for-line port of ``sota/common.py:evaluate_securedact``'s per-document
    assembly: the union of the base/BardsAI/GLiNER category sets, the generic BGE
    contribution for the four GEN4 categories, and the gated GENETIC
    decomposition. The political/sex-life decomposition booster is not active in
    the validated a9-sota-001 artifact (its frozen decomposition file contained
    only genetic hypotheses), so political/sex-life derive from generic BGE plus
    the detector stack exactly as the freeze manifest records.
    """

    stack = (
        set(sec)
        | set(bard)
        | set(gliner)
        | {category for category in GEN4 if gen.get(category, 0.0) >= FROZEN_G}
    )
    prop: set[EntityType] = set()
    if _genetic_decision(sec, bard, gliner, gen, gen_dec):
        prop.add(EntityType.GENETIC_DATA)
    return stack | prop
