"""Provider-independent privacy primitives for Securedact."""

from .api import (
    ErrorCode,
    PrepareOutcome,
    PrepareResult,
    PrepareStatus,
    RedactionRequest,
    ResponseMode,
    RestorationRequest,
    RestorationResult,
    ReviewOption,
    SafeFinding,
    SecuredactConfigurationError,
    SecuredactEngine,
    SecuredactError,
)
from .app_paths import SecuredactPaths
from .engine import PrivacyEngine
from .evaluation import EvaluationReport, evaluate_corpus, load_corpus
from .model_management import (
    InstalledModel,
    IntegrityStatus,
    ModelInstallErrorCode,
    ModelInstallProgress,
    ModelInstallResult,
    ModelInstallStage,
    ModelManagementError,
    ModelManager,
    ModelManifest,
    ModelManifestFile,
    ModelState,
    ModelStatus,
    verify_model_pack,
)
from .models import (
    AnalysisResult,
    Detection,
    DetectionSource,
    EntityType,
    FindingDecision,
    IndirectDisclosureRisk,
    PartialMatch,
    PrivacyAction,
    RedactionMode,
    RedactionResult,
    ResidualScanResult,
    ReviewAction,
    ReviewDecision,
    SanitizationAudit,
    SensitiveAssertion,
    Severity,
    TextSpan,
)
from .policies import AutomaticPseudonymizationRule, Policy, PolicyRegistry
from .policy_loader import (
    AUTOMATIC_PSEUDONYMIZATION_ENV,
    LocalPolicyLoader,
    PolicyLoadError,
    PolicyLoadErrorCode,
    load_policy_registry_from_environment,
)
from .production import PRODUCTION_DETERMINISTIC_DETECTORS, build_production_engine
from .profile_storage import PrivacyConfiguration, PrivacyProfileStore
from .restoration import (
    RestorationErrorCode,
    RestorationSessionError,
    RestorationVault,
)
from .taxonomy import (
    CATEGORY_DEFINITIONS,
    CRITICAL_TYPES,
    SPECIAL_CATEGORY_TYPES,
    CategoryGroup,
    EntityDefinition,
    category_metadata,
)

__all__ = [
    "AUTOMATIC_PSEUDONYMIZATION_ENV",
    "CATEGORY_DEFINITIONS",
    "CRITICAL_TYPES",
    "PRODUCTION_DETERMINISTIC_DETECTORS",
    "SPECIAL_CATEGORY_TYPES",
    "AnalysisResult",
    "AutomaticPseudonymizationRule",
    "CategoryGroup",
    "Detection",
    "DetectionSource",
    "EntityDefinition",
    "EntityType",
    "ErrorCode",
    "EvaluationReport",
    "FindingDecision",
    "IndirectDisclosureRisk",
    "InstalledModel",
    "IntegrityStatus",
    "LocalPolicyLoader",
    "ModelInstallErrorCode",
    "ModelInstallProgress",
    "ModelInstallResult",
    "ModelInstallStage",
    "ModelManagementError",
    "ModelManager",
    "ModelManifest",
    "ModelManifestFile",
    "ModelState",
    "ModelStatus",
    "PartialMatch",
    "Policy",
    "PolicyLoadError",
    "PolicyLoadErrorCode",
    "PolicyRegistry",
    "PrepareOutcome",
    "PrepareResult",
    "PrepareStatus",
    "PrivacyAction",
    "PrivacyConfiguration",
    "PrivacyEngine",
    "PrivacyProfileStore",
    "RedactionMode",
    "RedactionRequest",
    "RedactionResult",
    "ResidualScanResult",
    "ResponseMode",
    "RestorationErrorCode",
    "RestorationRequest",
    "RestorationResult",
    "RestorationSessionError",
    "RestorationVault",
    "ReviewAction",
    "ReviewDecision",
    "ReviewOption",
    "SafeFinding",
    "SanitizationAudit",
    "SecuredactConfigurationError",
    "SecuredactEngine",
    "SecuredactError",
    "SecuredactPaths",
    "SensitiveAssertion",
    "Severity",
    "TextSpan",
    "build_production_engine",
    "category_metadata",
    "evaluate_corpus",
    "load_corpus",
    "load_policy_registry_from_environment",
    "verify_model_pack",
]
